project:
  type: website
  render:
    - "*.qmd"
    - "!submission/**"

website:
  title: "Rupinder Kaur — MBA Portfolio"
  navbar:
    logo: assets/images/logo-rk.svg
    right:
      - text: Home
        file: index.qmd
      - text: Resume
        file: resume.qmd
      - text: Projects
        file: projects.qmd
      - text: Skills
        file: skills.qmd
      - text: Leadership
        file: leadership.qmd
      - text: Contact
        file: contact.qmd
  page-footer:
    center: "©2025 Rupinder Kaur"
    right: "Built with Quarto"
  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    smooth-scroll: true
