project:
  type: website

website:
  title: "Rupinder Kaur — MBA Portfolio"
  description: "Multi-page MBA portfolio showcasing leadership, experience, projects, and skills."
  navbar:
    logo: assets/images/logo-placeholder.svg
    right:
      - text: Appendix
        file: appendix.qmd
      - text: Home
        file: index.qmd
      - text: Resume
        file: resume.qmd
      - text: Projects
        file: projects.qmd
      - text: Skills
        file: skills.qmd
      - text: Leadership
        file: leadership.qmd
      - text: Contact
        file: contact.qmd
  page-footer:
    center: "@2025 © {year} Rupinder Kaur"
    right: "Built with Quarto"
  search: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    smooth-scroll: true
    css: styles.css
    anchor-sections: true
